apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  labels:
    app.kubernetes.io/name: model-api
    app.kubernetes.io/component: secrets
type: Opaque
stringData:
  REDIS_PASSWORD: "REPLACE_WITH_PROD_REDIS_PASSWORD"
  POSTGRES_PASSWORD: "REPLACE_WITH_PROD_POSTGRES_PASSWORD"
  KRAKEND_DB_PASSWORD: "REPLACE_WITH_PROD_KRAKEND_DB_PASSWORD"
