apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  labels:
    app.kubernetes.io/name: model-api
    app.kubernetes.io/component: secrets
type: Opaque
stringData:
  REDIS_PASSWORD: "redis-dev-password"
  POSTGRES_PASSWORD: "krakend-dev-password"
  KRAKEND_DB_PASSWORD: "krakend-dev-password"
