"""Scaffold a new service definition, model stub, and dev secrets."""

from __future__ import annotations

import argparse
import re
import secrets
import subprocess
import sys
from pathlib import Path

import yaml

SERVICE_YAML_TEMPLATE = """# Maintainer touch surface — edit by hand, then: make render SERVICE={service_id}
service_id: {service_id}
display_name: {display_name}

# Dev K8s namespace (prod namespace lives in prod.overlay.yaml).
kubernetes:
  namespace: {service_id}

model:
  module: {module}
  class: {class_name}
  bento_name: {service_id}
  source: {model_source}          # hugging_face | private
  id: {model_id}
  revision: ""                     # pin HF revision for reproducible builds
  cache_dir: ""                    # required when source: private (absolute path)

oidc:
  application_slug: {service_id}
  client_id: {service_id}-api
  provider_name: {service_id}-provider
  app_display_name: "{display_name}"

dev_access:
  api_port: {api_port}             # KrakenD port-forward (avoid collisions — see docs/adding-a-service.md)
  authentik_port: {authentik_port}
  authentik_https_port: {authentik_https_port}
"""


def _snake(name: str) -> str:
    return re.sub(r"[^a-z0-9]+", "_", name.lower()).strip("_")


def _class_name(service_id: str) -> str:
    return "".join(part.capitalize() for part in service_id.replace("-", "_").split("_")) + "Service"


def scaffold(
    service_id: str,
    model_id: str,
    model_source: str,
    api_port: int,
    authentik_port: int,
) -> None:
    repo_root = Path(__file__).resolve().parents[2]
    service_dir = repo_root / "services" / service_id
    if service_dir.exists():
        raise FileExistsError(f"Service already exists: {service_dir}")

    module = f"models.{_snake(service_id)}"
    class_name = _class_name(service_id)
    display_name = service_id.replace("-", " ").title() + " API"

    service_dir.mkdir(parents=True)
    (service_dir / "service.yaml").write_text(
        SERVICE_YAML_TEMPLATE.format(
            service_id=service_id,
            display_name=display_name,
            module=module,
            class_name=class_name,
            model_source=model_source,
            model_id=model_id,
            api_port=api_port,
            authentik_port=authentik_port,
            authentik_https_port=authentik_port + 42,
        ),
        encoding="utf-8",
    )

    overlay_example = {
        "kubernetes": {"namespace": "REPLACE_WITH_PROD_NAMESPACE"},
        "auth": {
            "mode": "external",
            "jwk_url": "REPLACE_WITH_HTTPS_JWKS_URL",
            "issuer": "REPLACE_WITH_HTTPS_ISSUER",
            "disable_jwk_security": False,
            "operation_debug": False,
        },
        "ingress": {
            "enabled": True,
            "host": f"REPLACE_WITH_{service_id.upper().replace('-', '_')}_HOST",
            "ingress_class": "haproxy-4",
        },
        "image": {"registry": "ghcr.io/luisfpal", "tag": "latest", "digest": ""},
        "registry": {"ghcr_owner": "luisfpal"},
    }
    (service_dir / "prod.overlay.yaml.example").write_text(
        "# yaml-language-server: $schema=../../ml_platform/schemas/prod-overlay.schema.json\n"
        + yaml.safe_dump(overlay_example, sort_keys=False),
        encoding="utf-8",
    )

    model_path = repo_root / "src" / "models" / f"{_snake(service_id)}.py"
    model_path.parent.mkdir(parents=True, exist_ok=True)
    if not model_path.exists():
        model_path.write_text(
            f'''"""BentoML service for {service_id}."""

import bentoml

from core.image_classification_service import ImageClassificationModelService


@bentoml.service(name="{service_id}", traffic={{"timeout": 300}})
class {class_name}(ImageClassificationModelService):
    """Image classification model service."""
''',
            encoding="utf-8",
        )

    print(f"Scaffolded {service_dir} and {model_path}")


def _write_secrets_local(service_id: str) -> Path:
    repo_root = Path(__file__).resolve().parents[2]
    secrets_path = repo_root / "services" / service_id / "secrets.local.yaml"
    if secrets_path.exists():
        return secrets_path

    secrets_data = {
        "redis_password": secrets.token_urlsafe(32),
        "postgres_password": secrets.token_urlsafe(32),
        "oidc_client_secret": "REPLACE_WITH_AUTHENTIK_CLIENT_SECRET",
    }
    secrets_path.write_text(
        "# Auto-generated by make onboard — set oidc_client_secret from Authentik.\n"
        + yaml.safe_dump(secrets_data, sort_keys=False),
        encoding="utf-8",
    )
    print(f"Created {secrets_path}")
    return secrets_path


def onboard(
    service_id: str,
    model_id: str,
    model_source: str,
    api_port: int,
    authentik_port: int,
) -> None:
    """Scaffold, render, validate, and create secrets.local.yaml."""
    repo_root = Path(__file__).resolve().parents[2]
    scaffold(service_id, model_id, model_source, api_port, authentik_port)
    _write_secrets_local(service_id)

    python = sys.executable
    subprocess.run(
        [python, "-m", "ml_platform.generator.render", "--service", service_id, "--env", "dev"],
        cwd=repo_root,
        check=True,
    )
    subprocess.run(
        [python, "-m", "ml_platform.generator.validate", "--service", service_id],
        cwd=repo_root,
        check=True,
    )
    print(
        f"Onboard complete: edit src/models/{_snake(service_id)}.py, "
        f"set oidc_client_secret, then make deploy SERVICE={service_id}"
    )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    sub = parser.add_subparsers(dest="command", required=True)

    scaffold_p = sub.add_parser("scaffold", help="Create service.yaml + model stub only")
    scaffold_p.add_argument("--service", required=True)
    scaffold_p.add_argument("--model-id", required=True)
    scaffold_p.add_argument("--model-source", default="hugging_face")
    scaffold_p.add_argument("--api-port", type=int, default=8080)
    scaffold_p.add_argument("--authentik-port", type=int, default=9001)

    onboard_p = sub.add_parser("onboard", help="Scaffold + render + validate + secrets.local.yaml")
    onboard_p.add_argument("--service", required=True)
    onboard_p.add_argument("--model-id", required=True)
    onboard_p.add_argument("--model-source", default="hugging_face")
    onboard_p.add_argument("--api-port", type=int, default=8080)
    onboard_p.add_argument("--authentik-port", type=int, default=9001)

    args = parser.parse_args(argv)
    if args.command == "scaffold":
        scaffold(
            args.service,
            args.model_id,
            args.model_source,
            args.api_port,
            args.authentik_port,
        )
    else:
        onboard(
            args.service,
            args.model_id,
            args.model_source,
            args.api_port,
            args.authentik_port,
        )
    return 0


if __name__ == "__main__":
    sys.exit(main())
